
name: "update pins"

on:
  workflow_dispatch:
  schedule:
    - cron: '25 4,16 * * *'

jobs:
  update_pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - run: pip install pip-tools
      - run: pip-compile --allow-unsafe --generate-hashes pins/requirements.in -o pins/requirements-3.7.txt

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pip install pip-tools
      - run: pip-compile --allow-unsafe --generate-hashes pins/requirements.in -o pins/requirements-3.8.txt

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install pip-tools
      - run: pip-compile --allow-unsafe --generate-hashes pins/requirements.in -o pins/requirements-3.9.txt

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pip-tools
      - run: pip-compile --allow-unsafe --generate-hashes pins/requirements.in -o pins/requirements-3.10.txt

      - id: commit
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "install-pinned bot"
            git config --global user.email "install-pinned@users.noreply.github.com"
            git add --all
            ver=$(curl -Ls https://pypi.org/pypi/pip-tools/json | jq -r .info.version)
            git commit -m "update pins (pip-tools $ver)"
            commit=$(git rev-parse HEAD)
            tag=$(date -uIminutes | sed s/+00:00/Z/ | sed s/:/./g)_pip-tools_$ver
            git tag $tag
            sed -i -E "s/@[0-9a-f]{40}/@$commit/g" README.md
            git commit -am "update README.md (pip-tools $ver)"
            git push
            git push --tags
            echo "::set-output name=tag::$tag"
            echo "::set-output name=ver::$ver"
          fi
      - if: steps.commit.outputs.tag
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
        with:
          name: pip-tools ${{ steps.commit.outputs.ver }}
          tag_name: ${{ steps.commit.outputs.tag }}
